# lab:
#   Mono:
#     black:
#       max:
#       - 89
#       - 255
#       - 255
#       min:
#       - 0
#       - 0
#       - 0
#     blue:
#       max:
#       - 255
#       - 136
#       - 120
#       min:
#       - 0
#       - 0
#       - 0
#     green:
#       max:
#       - 255
#       - 110
#       - 255
#       min:
#       - 47
#       - 0
#       - 135
#     red:
#       max:
#       - 255
#       - 255
#       - 255
#       min:
#       - 0
#       - 150
#       - 130
#     white:
#       max:
#       - 255
#       - 255
#       - 255
#       min:
#       - 193
#       - 0
#       - 0
#   Stereo:
#     black:
#       max:
#       - 90
#       - 255
#       - 255
#       min:
#       - 0
#       - 0
#       - 0
#     blue:
#       max:
#       - 255
#       - 130
#       - 118
#       min:
#       - 0
#       - 0
#       - 0
#     green:
#       max:
#       - 255
#       - 110
#       - 255
#       min:
#       - 47
#       - 0
#       - 135
#     red:
#       max:
#       - 255
#       - 255
#       - 255
#       min:
#       - 0
#       - 150
#       - 130
#     white:
#       max:
#       - 255
#       - 255
#       - 255
#       min:
#       - 193
#       - 0
#       - 0
#     yellow:
#       max:
#       - 248
#       - 165
#       - 210
#       min:
#       - 0
#       - 113
#       - 87
#     # yellow:
#     #   max:
#     #   - 255
#     #   - 255
#     #   - 120
#     #   min:
#     #   - 180
#     #   - 180
#     #   - 0
# size:
#   height:
#   - 480
#   width:
#   - 640


lab:
  Mono:
    black:
      max:
      - 89
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 255
      - 136
      - 120
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 110
      - 255
      min:
      - 47
      - 0
      - 135
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 150
      - 130
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
  Stereo:
    black:
      max:
      - 90
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 255
      - 130
      - 118
      min:
      - 0
      - 0
      - 0
    green:
      max:
      - 255
      - 110
      - 255
      min:
      - 47
      - 0
      - 135
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 150
      - 130
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 165
      - 104
      - 151
size:
  height:
  - 480
  width:
  - 640
