apiVersion: v1
kind: Service
metadata:
  name: lane-detect-server
spec:
  type: NodePort 
  ports:
    - protocol: TCP
      port: 5005         # Expose service on port 80 externally
      targetPort: 5005  # Map to container's port 5000
      nodePort: 30055   # keep OBd service nodePort= 30006(just to avoid confusion)
  selector:
    app: lane-detect-app
